"""added ItnScheduleTemp

Revision ID: 0db2126a7dbc
Revises: 9292c98d30ad
Create Date: 2020-09-01 16:10:57.585356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db2126a7dbc'
down_revision = '9292c98d30ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itn_schedule_temp',
    sa.Column('itn', sa.String(length=33), nullable=False),
    sa.Column('utc', sa.DateTime(), nullable=False),
    sa.Column('forecast_vol', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('reported_vol', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('itn', 'utc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itn_schedule_temp')
    # ### end Alembic commands ###
