"""ibex_table

Revision ID: 347157bcb8de
Revises: b4d0df43d756
Create Date: 2020-09-25 12:49:34.058574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347157bcb8de'
down_revision = 'b4d0df43d756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibex_data',
    sa.Column('utc', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('forecast_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('volume', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('utc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibex_data')
    # ### end Alembic commands ###
