"""added invoicing label__production

Revision ID: 38711a333691
Revises: fedbcb1df714
Create Date: 2021-01-08 12:24:40.531038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38711a333691'
down_revision = 'fedbcb1df714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('invoicing_label', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'contract', ['invoicing_label'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='unique')
    op.drop_column('contract', 'invoicing_label')
    # ### end Alembic commands ###
