"""forecasted volume added to subcontract

Revision ID: 6312501f6742
Revises: 941adab262c7
Create Date: 2020-08-25 21:01:57.184569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6312501f6742'
down_revision = '941adab262c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_contract', sa.Column('forecast_vol', sa.Numeric(precision=12, scale=6), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_contract', 'forecast_vol')
    # ### end Alembic commands ###
