"""invoice_table

Revision ID: 7fbf4301e9c8
Revises: f677fd364787
Create Date: 2020-11-04 16:18:53.544350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbf4301e9c8'
down_revision = 'f677fd364787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('total_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('total_sum', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grid_sum', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('zko_sum', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('akciz_sum', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('additional_tax_sum', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ref_file_name', sa.String(length=256), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('maturity_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'price'),
    sa.UniqueConstraint('ref_file_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    # ### end Alembic commands ###
