"""last update added to subcontract

Revision ID: 9292c98d30ad
Revises: 6312501f6742
Create Date: 2020-08-26 11:17:40.172477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9292c98d30ad'
down_revision = '6312501f6742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_contract', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_contract', 'last_updated')
    # ### end Alembic commands ###
