"""mail_table

Revision ID: 9b081325b8f7
Revises: 7fbf4301e9c8
Create Date: 2020-11-12 22:20:20.899610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b081325b8f7'
down_revision = '7fbf4301e9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_constraint('invoice_ibfk_2', 'invoice', type_='foreignkey')
    op.create_foreign_key(None, 'invoice', 'invoice_group', ['invoice_group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('invoice_group', sa.Column('email_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoice_group', 'contractor', ['email_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_group', type_='foreignkey')
    op.drop_column('invoice_group', 'email_id')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.create_foreign_key('invoice_ibfk_2', 'invoice', 'invoice_group', ['invoice_group_id'], ['id'])
    op.drop_table('mail')
    # ### end Alembic commands ###
