"""Added DistributionTemp table

Revision ID: a2f28061e0df
Revises: 0108dba5d92a
Create Date: 2020-10-19 14:41:06.858461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f28061e0df'
down_revision = '0108dba5d92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_temp',
    sa.Column('itn', sa.String(length=33), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('tariff', sa.String(length=256), nullable=False),
    sa.Column('calc_amount', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('correction_note', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=128), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['itn'], ['itn_meta.itn'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itn', 'start_date', 'price', 'value', 'correction_note')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribution_temp')
    # ### end Alembic commands ###
