"""added description to invoicing group model

Revision ID: b4d0df43d756
Revises: 3f40ec244b90
Create Date: 2020-09-09 05:30:49.508031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d0df43d756'
down_revision = '3f40ec244b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_group', sa.Column('description', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_group', 'description')
    # ### end Alembic commands ###
