"""adding make invoice to sub contract

Revision ID: cc693aa79e89
Revises: a2f28061e0df
Create Date: 2020-10-26 16:18:55.360879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc693aa79e89'
down_revision = 'a2f28061e0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_contract', sa.Column('make_invoice', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_contract', 'make_invoice')
    # ### end Alembic commands ###
