"""forecast type table

Revision ID: cdf312632e16
Revises: 07612b4fc718
Create Date: 2021-01-04 16:02:07.486954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf312632e16'
down_revision = '07612b4fc718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_type',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_coeffs',
    sa.Column('utc', sa.DateTime(), nullable=False),
    sa.Column('forecast_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.Numeric(precision=9, scale=7), nullable=False),
    sa.ForeignKeyConstraint(['forecast_type_id'], ['forecast_type.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('utc', 'forecast_type_id')
    )
    op.add_column('sub_contract', sa.Column('forecast_type_id', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(None, 'sub_contract', 'forecast_type', ['forecast_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_contract', type_='foreignkey')
    op.drop_column('sub_contract', 'forecast_type_id')
    op.drop_table('forecast_coeffs')
    op.drop_table('forecast_type')
    # ### end Alembic commands ###
