"""mailing date added to invoice

Revision ID: dae31c676bb3
Revises: e0e880ea5480
Create Date: 2021-01-11 11:15:01.502540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae31c676bb3'
down_revision = 'e0e880ea5480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('mailing_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'mailing_date')
    # ### end Alembic commands ###
