"""added invoicing_label to contracts _ test

Revision ID: e0e880ea5480
Revises: cdf312632e16
Create Date: 2021-01-08 10:29:32.700644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e880ea5480'
down_revision = 'cdf312632e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('invoicing_label', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'contract', ['invoicing_label'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='unique')
    op.drop_column('contract', 'invoicing_label')
    # ### end Alembic commands ###
