"""tariff_added itn, price removed from subcontract

Revision ID: ea9b99c7b8cb
Revises: f6aaccb419a7
Create Date: 2020-09-28 12:01:23.989543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9b99c7b8cb'
down_revision = 'f6aaccb419a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff', sa.Column('itn', sa.String(length=33), nullable=True))
    op.create_foreign_key(None, 'tariff', 'itn_meta', ['itn'], ['itn'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tariff', type_='foreignkey')
    op.drop_column('tariff', 'itn')
    # ### end Alembic commands ###
