"""adding upper lower limit to tariff

Revision ID: f677fd364787
Revises: cc693aa79e89
Create Date: 2020-10-27 08:53:53.028330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f677fd364787'
down_revision = 'cc693aa79e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff', sa.Column('lower_limit', sa.Numeric(precision=8, scale=7), nullable=False))
    op.add_column('tariff', sa.Column('upper_limit', sa.Numeric(precision=8, scale=7), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariff', 'upper_limit')
    op.drop_column('tariff', 'lower_limit')
    # ### end Alembic commands ###
