"""tariff_table

Revision ID: f6aaccb419a7
Revises: 347157bcb8de
Create Date: 2020-09-26 06:32:33.697740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6aaccb419a7'
down_revision = '347157bcb8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itn_schedule_temp', sa.Column('tariff_id', sa.Integer(), nullable=False))
    op.add_column('tariff', sa.Column('end_hour', sa.SmallInteger(), nullable=False))
    op.add_column('tariff', sa.Column('start_hour', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariff', 'start_hour')
    op.drop_column('tariff', 'end_hour')
    op.drop_column('itn_schedule_temp', 'tariff_id')
    # ### end Alembic commands ###
